/**
 * Generated by scripts/registry-groups.mjs. Edit the README tables instead.
 */
import type { ComponentGroups, BlockGroups } from "./registry-groups-types";

export const componentGroups: ComponentGroups = [
  {
    title: "Actions",
    groups: [
      { title: "Buttons", items: ["button", "action-button", "split-button", "button-group", "floating-button-group", "expanding-button-group", "copy-button", "confirm-morph"] },
      { title: "Gestures", items: ["hold-to-confirm", "swipe-actions"] },
      { title: "Menus", items: ["dropdown-menu", "context-menu", "user-menu"] },
      { title: "Theme", items: ["theme-switch", "theme-switch-eclipse", "theme-switch-split", "theme-switch-rise"] },
    ],
  },
  {
    title: "Inputs",
    groups: [
      { title: "Text fields", items: ["input", "textarea", "password-field", "password-strength", "search-field", "expanding-search", "inline-edit"] },
      { title: "Special inputs", items: ["number-field", "money-input", "phone-input", "tag-input", "mention-input", "shortcut-recorder"] },
      { title: "Selects", items: ["select", "combobox", "multi-select", "morph-select", "chip-group"] },
      { title: "Toggles", items: ["radio-cards", "billing-toggle", "checkbox", "radio-group", "switch", "segmented-control"] },
      { title: "Sliders", items: ["slider"] },
      { title: "Pickers", items: ["calendar", "date-picker", "date-range-picker", "time-picker", "color-picker"] },
      { title: "Editors", items: ["rich-text-editor", "signature-pad", "file-dropzone"] },
    ],
  },
  {
    title: "Disclosure",
    groups: [
      { title: "Navigation", items: ["tabs", "breadcrumb", "pagination"] },
      { title: "Expand", items: ["scroll-area", "accordion", "expandable-card", "resizable-panels"] },
      { title: "Overlays", items: ["dialog", "drawer", "bottom-sheet", "popover", "hover-card", "tooltip"] },
    ],
  },
  {
    title: "Feedback",
    groups: [
      { title: "Messages", items: ["alert", "toast", "toast-stack", "announcement-bar"] },
      { title: "Progress", items: ["progress", "skeleton", "stepper", "usage-meter"] },
    ],
  },
  {
    title: "Data",
    groups: [
      { title: "Avatars", items: ["avatar", "avatar-group", "badge"] },
      { title: "Cards", items: ["card", "metric-card", "empty-state"] },
      { title: "Charts", items: ["line-chart", "bar-chart", "donut-chart", "streamgraph", "brush-chart", "waffle-chart", "slope-chart", "sparkline", "gauge", "activity-heatmap", "animated-counter", "ridgeline", "treemap"] },
      { title: "Tables", items: ["sortable-data-table", "tree-view", "filter-toolbar", "code-block", "json-viewer"] },
      { title: "Activity", items: ["timeline", "comment-thread", "chat-thread"] },
      { title: "Media", items: ["image-compare", "carousel", "card-stack"] },
    ],
  },
  {
    title: "Text",
    groups: [
      { title: "Text effects", items: ["text-reveal", "in-view-title", "text-morph", "text-shimmer"] },
    ],
  },
  {
    title: "Special",
    groups: [
      { title: "Type", items: ["slot-text"] },
    ],
  },
];

export const blockGroups: BlockGroups = [
  { title: "App shell", items: ["page-header", "command-palette", "notification-center", "empty-states"] },
  { title: "Auth", items: ["signup-form", "sign-in", "login-centered", "otp-input"] },
  { title: "Pricing", items: ["plan-comparison"] },
  { title: "Media", items: ["file-upload"] },
  { title: "Heroes", items: ["hero-section"] },
  { title: "Features", items: ["comparison-table"] },
  { title: "Social proof", items: ["logo-marquee", "stats-band"] },
  { title: "Content", items: ["changelog-feed", "faq-section", "contact-section", "blog-grid"] },
  { title: "Headers and footers", items: ["site-header", "site-footer", "cta-section", "newsletter-signup"] },
];
